### ISSUE TITLE
Replace node-rfc

### ISSUE THREAD

**Issue by simonegaffurini** [RegestaItalia/trm-core#61]
With the [node-rfc end of maintenance](https://github.com/SAP/PyRFC/issues/372), it's now a necessity implementing a rest api system connector.
This requires a new backend server package dedicated to exposing the apis.

**Comment by amarvin** [comment]
Resolved in 768e840215b72522a2e9c2b1a910aab322a44e4a. Note that instead you could have installed a pinned version of `node-rfc`, which is still available yet is yanked, with a warning.

**Comment by simonegaffurini** [comment]
@amarvin Yes, you are right. However, I took the opportunity to add a new connection option in addition to RFC: REST (which can be handy in pipelines, for example).
The node-rfc library is now optional, meaning you can still connect to the backend using RFC, but the library is no longer a dependency.
Cli client using the new core is coming soon
